### ISSUE TITLE
2 - Upgrade Wand - A wand that you can give players that will be used to upgrade gens in a radius

### ISSUE THREAD

**Issue by OpenSource03** [arcadiadevs/gensplus-issues#11]

**Comment by WePico** [comment]
That's great, we could choose the radius of the zone, for example, 10x10 or 5x5 or 3x3?

**Comment by OpenSource03** [comment]
> That's great, we could choose the radius of the zone, for example, 10x10 or 5x5 or 3x3?

Check #8 for more info :)
