### ISSUE TITLE
Problem with /plot delete command and generators in GensPlus and PlotSquared 🌱🏗️

### ISSUE THREAD

**Issue by WePico** [arcadiadevs/gensplus-issues#14]
📝 **Issue Description:**
I'm currently facing an issue with the combined use of GensPlus and PlotSquared plugins on my Minecraft server. When I execute the `/plot delete` command to remove all plots in PlotSquared, it also deletes all generators placed using GensPlus. However, after running this command, the generators are still considered "placed," which is not the expected behavior.

🔍 **Steps to Reproduce:**
1. Make sure you have both GensPlus and PlotSquared plugins installed and active on the server.
2. Place several generators at different locations on plots in the world managed by PlotSquared.
3. Execute the `/plot delete` command to remove all plots.

💡 **Expected Behavior:**
The plots should be deleted, resulting in the removal of generators placed with GensPlus. After running the `/plot delete` command, the generators should no longer be considered "placed."

🐛 **Current Behavior:**
The plots are successfully removed, but the generators remain considered "placed" in the world despite their physical removal. This can lead to inconsistencies in the economy and server management.

ℹ️ **Additional Information:**
- GensPlus Version: [1.3.0-beta1]
- PlotSquared Version: [7.0.0 RC.3]

I want to emphasize that both of these plugins are fantastic and bring a wonderful gameplay experience to our server. However, this issue with the `/plot delete` command and generators could disrupt the overall gameplay balance. I hope this can be resolved to enhance the overall player experience.

Thank you very much for your hard work on these plugins and for your assistance in addressing this issue.

Best regards,
WePico 👋

**Comment by OpenSource03** [comment]
This issue has been fixed in 1.3.0-beta2 which will be released during the next week.
