### ISSUE TITLE
Make it possible to use commands from the console

### ISSUE THREAD

**Issue by bluryisacutie** [arcadiadevs/gensplus-issues#15]
so basically i want to be able to create a /start command in skript where it gives u a generator, but i realized the command doesn't work when u execute it as a console command, also i want to be able to give someone a gen when they buy it from the shop

here's the skript code

command /start:
	trigger:
		if player has permission "start.use":
			console command "mv tp %player% beta"
			wait 1 second
			player command "plot auto"
			execute console command  "gensplus give %player% 1 1"
			console command "pex user %player% remove start.use"
			send "&dAspireGN &8| &eYou've Begun Your Journey"
		else:
			send "&dAspireGN &8| &eYou've Already Started Your Journey"

**Comment by xdDirti** [comment]
In general, this is the inability to give players generators using a console command.

It's also fustrating because it's impossible to give gens through crates and "monthly" crates.

**Comment by bluryisacutie** [comment]
whats the permission for the sell command bc my player's don't have
permission to use it

**Comment by OpenSource03** [comment]
Added in 1.3.0-beta2, releasing somewhere next week
