### ISSUE TITLE
Gen Upgrade Bug

### ISSUE THREAD

**Issue by bluryisacutie** [arcadiadevs/gensplus-issues#16]
so basically when i upgrade my gens, its always $1,000, no matter the balance, i didn't change anything in the config, and all the prices in the config are the same.

i dont know how to reproduce it because it was always like this, how do i fix?

**Comment by OpenSource03** [comment]
Hi,

technically, this was not a bug, but I understand that the current system is quite a bit confusing. I made adjustments on how the system works, so now if you have tier 2 for 2000, and tier 3 price is 3000, it will require you to pay 3000. Previously, it would just require you to pay the difference between those two, which would be 1000.

So if you had (like in the default config) gens with prices of 1000 2000 3000 4000, it would always be $1000 for each and every upgrade. Now it will be 2000 3000 4000.
