### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by TristanChen122** [arcadiadevs/gensplus-issues#20]
Events are not working as they should, no broadcast nor anything different happened during events.

**Comment by OpenSource03** [comment]
Hi, we were unable to find any issues with events, except for the drop event not working when holograms are disabled.

We have implemented a fix for the drop event. It will be released in the next update.

For anything else, you will need to provide more info:

- Your server version
- Your MC version
- Your GensPlus version
- List of plugins installed
- Your GensPlus config

When provided, I will reopen the issue :)
