### ISSUE TITLE
Allow multiplier in sellwand name

### ISSUE THREAD

**Issue by marcelpkg** [arcadiadevs/gensplus-issues#23]
The title says it all, it would be easier for players to exchange sell wands with 100% cetrainty

![image](https://github.com/arcadiadevs/gensplus-issues/assets/64794665/4cd39d07-e1c4-455b-86fc-1197fbcb140a)

**Comment by Marko675** [comment]
We have added placeholder for multipliers (%multiplier%). We will release new update soon!
