### ISSUE TITLE
High prices dont have formatting in messages

### ISSUE THREAD

**Issue by marcelpkg** [arcadiadevs/gensplus-issues#24]
**Buying Generators**
![image](https://github.com/arcadiadevs/gensplus-issues/assets/64794665/b8953dc9-2fad-4a20-88ae-c0cdd8adc5ca)

**Upgrading generators**
![image](https://github.com/arcadiadevs/gensplus-issues/assets/64794665/e9e8e58d-8744-4cdb-8814-3e46e097738f)

**Comment by Marko675** [comment]
Those numbers are above java's max double limit. Implementing a system for those kinds of numbers would take too much time... as most of the users don't use such high numbers.

**Comment by Marko675** [comment]
We are now formatting this type of numbers as well!
