### ISSUE TITLE
Gen Limit

### ISSUE THREAD

**Issue by Broascaa** [arcadiadevs/gensplus-issues#29]
**Describe the bug**
Hello! I'm using IridiumSkyblock on my server and i can't place anymore generator on a new create island because i have another 20 place generators on a deleted island (the default limit is 20 generators)

**To Reproduce**
1. Create a new island, place the maximum default limit of generators
2. Delete that island
3. Create another island and try to place another generator

**Expected behavior**
To be able to place generators on a new created island

**Screenshots**
-

**Additional info (please complete the following information):**
 - Spigot Version: git-Purpur-2044 (MC: 1.20.1)
 - Using ViaVersion/ProtocolSupport: yes (ViaVersion)
 - Your MC version: 1.20.1 - Optifine

**Additional context**
-

**Comment by OpenSource03** [comment]
This issue is now fixed and an update will be released soon to address it. It was caused due to IridiumSkyblock not ACTUALLY removing the island, as even when you do /is remove, the island still exists in the world for some reason...

Expect the update in a day or two.
