### ISSUE TITLE
Player Lag Issues & New Features

### ISSUE THREAD

**Issue by massacred** [arcadiadevs/gensplus-issues#30]
Hello currently this plugin can make players lag a lot when items spawn in. This is because they aren't being stacked for around 1-2 seconds due to the plugin not linking to a stacking plugin. I would really like to see the dev combat this issue by adding support for pugins like; WildStacker, RoseStacker & others.

**PLAYER LAG EXAMPLE**
https://imgur.com/a/QWDvmMI

I'd also like to add this gens plugin could really do with more features as there are now plugins with a lot more features and devs introducing things weekly. I'm not asking you to exactly copy this plugins features but i'll link it hoping it will help with ideas:
https://builtbybit.com/resources/nextgens-minecraft-gens-tycoon-plugin.30903/

**Comment by Marko675** [comment]
The lag that you showed in the video has been fixed in the latest version. In terms of new features, we are constantly adding new features that people request.
