### ISSUE TITLE
generator upgrade price no space is filled

### ISSUE THREAD

**Issue by iKingFe** [arcadiadevs/gensplus-issues#33]
how to change the generator upgrade price? Give me a detailed and clear example of where to place the coding.

**Comment by OpenSource03** [comment]
We already replied in your last issue… The answer was more than simple to understand. If you have gen with tier 1 with price of 2000, and you set price of gen 3 as 3000, upgrade price will be 1000. Basically every time you want to upgrade from tier a to tier b, the price is calculated as tier b price - tier 1 price.

if you have tier 5 gen with price 4000 and tier 6 with price of 7000, the price for upgrade will be 7000 - 4000 = 3000

Config is already well documented so I would suggest reading the comments to gain better understanding.
