### ISSUE TITLE
Bug about no drops

### ISSUE THREAD

**Issue by GamingPascal1** [arcadiadevs/gensplus-issues#35]
**Describe the bug**
The Generator does not Drop any items

**Expected behavior**
Simple bux fix or help to get this Bug done

**Screenshots**
https://i.imgur.com/4Eofvny.png

**Additional info (please complete the following information):**
 - Spigot Version: [e.g. Simple Spigot 1.20.1]
 - Using ViaVersion/ProtocolSupport [no , no]
 - Your MC version: [e.g. 1.20.1]

**Additional context**
nothing more

**Comment by OpenSource03** [comment]
Seems to be caused because you loaded the plugin with plugman or something similar, so your PlayerData was not loaded. To fix it, you just had to rejoin, I guess. This issue has been fixed.
