### ISSUE TITLE
The generator works with an offline owner.

### ISSUE THREAD

**Issue by EdoardoIon** [arcadiadevs/gensplus-issues#37]
**Is your feature request related to a problem? Please describe.**
I have a political server, and when a player puts a generator for his settlement, other citizens of this settlement can use it only when the owner of the generator is online, this is very inconvenient since the generator must work 24/7.

**Describe the solution you'd like**
The ability to enable the offline mode function for generators. When enabling this feature, generators should work even when the generator owner is not on the server.

**Describe alternatives you've considered**
Since this function is not currently in the plugin, I considered the decision to buy a bot that will stand on the server 24/7 and make the generators work.

**Additional context**
-

**Comment by Marko675** [comment]
We've added an option in the config to enable generators even if the owner is offline, and this update will be released in the upcoming days
