### ISSUE TITLE
Generators within Skyblock need to be validated at runtime. 

### ISSUE THREAD

**Issue by kylemarham** [arcadiadevs/gensplus-issues#41]
**Describe the bug**
Skyblock support with Gensplus seems to be pretty patchy.

If a user places gens on their island, then resets it, the gens no longer exist, but the plugin thinks they do.

Could something be added at runtime that checks if a generator exists, if it doesn't, remove it from the config?

We have users that have maxed their gen slots but don't actually have any gens down after they restart their islands.

**To Reproduce**
Install a Skyblock plugin
Install Gensplus
Place some generators on an island
Reset the island
Gens remain in the config 

**Expected behavior**
At runtime, each generator should be validated. If the block no longer exists, remove the generator from the config.

**Comment by OpenSource03** [comment]
Hi, can you please let us know which skyblock plugin are you using?

**Comment by kylemarham** [comment]
BSkyblock2, using BentoBox

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by OpenSource03** [comment]
The issue is fixed and an update will be posted shortly.
