### ISSUE TITLE
 error when activating holograms

### ISSUE THREAD

**Issue by 5blacklitzero3** [arcadiadevs/gensplus-issues#43]
The holograms only work on servers with 3 cores because I have another server with 2 cores and it sends errors and the plugin, the commands do not work

**Comment by Testic19** [comment]
> The holograms only work on servers with 3 cores because I have another server with 2 cores and it sends errors and the plugin, the commands do not work

Buy more cores

**Comment by Gamergys** [comment]
> > Los hologramas solo funcionan en servidores de 3 cores porque tengo otro servidor de 2 cores y manda errores y el plugin, los comandos no funcionan
> 
> Compra más núcleos

but the idea is that the plugin works on any type of server and capacity xd

**Comment by OpenSource03** [comment]
Thanks for mentioning that it sends errors, but unfortunately I can not know how to fix it or where the problem may be without you actually sending me the logs.

I'll close the issue until the required info is provided.
