### ISSUE TITLE
ItemSpawn: How do I make the head appear with the texture?

### ISSUE THREAD

**Issue by santiagoellis** [arcadiadevs/gensplus-issues#44]
How do I make the head appear with the texture?
I don't know how to do it, can you help me?

generators:
- name: '&fGenerador ▶ &e&lTRIGO'
  tier: 1
  price: 1000.0
  sellPrice: 10.0
  speed: 20
  spawnItem: player_head
  blockType: HAY_BLOCK
  lore: []
  itemSpawnLore:

**Comment by marlon-omc** [comment]
Did you discover how to make heads appear with custom textures?

**Comment by Marko675** [comment]
You can now make the head appear with the texture (ex. spawnItem: head:<name>)
