### ISSUE TITLE
Add a way to list gens locations /remove glitched gens while in game

### ISSUE THREAD

**Issue by Astolate** [arcadiadevs/gensplus-issues#48]
**Is your feature request related to a problem? Please describe.**
Add a way to view the locations and number of gens a player has and the limit they have in game.

**Describe the solution you'd like**
1. A way to list all placed gens for a player and possibly clear glitched gens in game.
2. A way to pull the number of a players gens through a command for staff so that we can see the numbers players see with %gensplus_gen_placed% / %gensplus_gen_limit% placeholders to help us troubleshoot issues for them.

**Comment by Marko675** [comment]
We have added the option to list and manage all generators using the /gensplus list command. This update will allow you to view the locations and number of generators a player has, as well as their generator limit, directly in-game. We will be publishing this update today.
