### ISSUE TITLE
Lapis Drops For Enchanting

### ISSUE THREAD

**Issue by Astolate** [arcadiadevs/gensplus-issues#49]
**Describe the bug**
Lapis drops may be used in enchanting table when crafting is set to false, additionally after enchanting it does not remove the lapis allowing for it to be used infinitely. 

**To Reproduce**
1. Go into your game and obtain a lapis gen.
2. Use the lapis in an enchanting table.
3. Enchants the item but does not consume the lapis in the process.

**Config**
```
Your gensplus config
```

**Expected behavior**
Lapis drops will not be usable in the enchanting table or they'll be usable but at least consumed in the process.

**Comment by Marko675** [comment]
The option to disable the enchanting table's interaction with generator drops and generators has been added. (we will post an update soon)
