### ISSUE TITLE
GensPlus Prevents using Hoes

### ISSUE THREAD

**Issue by Astolate** [arcadiadevs/gensplus-issues#50]
**Describe the bug**
The plugin prevents using hoes to turn blocks into farmland.

**To Reproduce**
1. Log into game and obtain a hoe
2. Click on any block that can be turned into farmland. Nothing happens.
3. Disable the plugin and try again, blocks turn into farmland as expected.

**Config**
```
[config(27).txt](https://github.com/arcadiadevs/gensplus-issues/files/15239192/config.27.txt)

```

**Expected behavior**
Using a hoe will allow you to turn a capable block into farmland.

**Comment by Marko675** [comment]
That's been fixed
