### ISSUE TITLE
OVERRIDES USE-PERMISSIONS does not function 

### ISSUE THREAD

**Issue by Astolate** [arcadiadevs/gensplus-issues#51]
**Describe the bug**
Commands to add or set the limits of gen slots do not override permissions limits.

**To Reproduce**
1. Give player a limit permission such as `gensplus.limit.20`
2. Set or add to the limit using `/gensplus addlimit 10`
3. It will say that the limit changes however no actual change is made to the player's limit it stays as the permission limit only and will not let player place additional gens.

**Config**
https://jumpshare.com/s/mXXDduCrzBJ9QoO10yV0

**Expected behavior**
Even with a set limit through permissions it should add more to their limit so if their limit is 20 and you add 10 it should allow them to put down 30.

**Additional info (please complete the following information):**
git-Paper-318, MC version 1.20.2

**Additional context**

**Comment by Marko675** [comment]
The issue has been fixed; command limits are now correctly combined with permission limits.
