### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by FluxBoys** [arcadiadevs/gensplus-issues#8]
- [x] #10
/wand sell [player] [multiplier] [uses]
/wand sell Player 2.5 500
You will be able to configure the lore of the wand aswell as giving an unlimited wand instead of limited uses

- [ ] #11
/wand upgrade [player] [radius] [uses]
/wand upgrade Player 3 100
You will be able to configure the lore of the wand aswell as giving an unlimited wand
3 = 3x3x3 radius

- [ ] #12
Lets say players start off with 10 slots and top rank gets 25 slots
Which means a top rank player starts off with 35 slots
Owner of the server will be able to reward the player with MORE slots on top of starting slots and rank slots
/gens slots give [player] [amount]
/gens slots remove [player] [amount]

- [ ] #13
/gens pickup

The first 3 basic features could be a GAME changer for this plugin and adds SO MUCH to it and freedom to the plugin and ways to attract more players

**Comment by OpenSource03** [comment]
- 3 can be done with other rankup plugins by using setlimit command on rankup, but we will also add the give and remove slots commands as well.
- 1 is added
- 2 is not planned right now
- 4 will not be added
