### ISSUE TITLE
Money left to upgrade message

### ISSUE THREAD

**Issue by xdDirti** [arcadiadevs/gensplus-issues#9]
My suggestion is that when player's upgrade, they are always met with:
You don't have enough money to upgrade!

I would like to suggest that instead of this, a message/placeholder like this is made:
You don't have enough money to upgrade! **($1,142,201/$2,000,000)**

It would up the user experience a lot, and I have received a lot of complains about it on my server.

**Comment by Marko675** [comment]
Thanks for the suggestion! We've added the detailed upgrade message in the latest builds (coming soon).
